### ISSUE TITLE
Inconsistência entre código e documentação.

### ISSUE THREAD

**Issue by igords-goncalves** [DiegoSilva94/FakeApiJs#1]
Olá, durante um teste técnico feito realizando esse repositório, eu encontrei uma pequena diferença entre uma nomeação de propriedade no código e na documentação que impacta diretamente a realização de requisições para a rota específica.

- Rota - `'/comments/update'`
- Trecho - `FakerApi.put('/comments/update', { post_id: 1, comment_id: 1, post: { content:'Comentario atualizado' } })`

O nome da terceira propriedade enviada no corpo da requisição deveria ser comment como conta no código da API.

Referência: 
- Arquivo: fakerApi.js/ts, 
- linha: 91

~~~~
        '/comments/update': function (instance, {post_id, comment_id, comment: {content}}) {
            const comment = instance._getComment(post_id, comment_id)
            comment.content = content
            instance._setComment(post_id, comment)
            return {
                success: true,
                message: 'Comentario atualizado'
            }
        },
~~~~

**Comment by DiegoSilva94** [comment]
Obrigado por notar, na verdade no index.html está incorreto o descritivo, o correto seria comment mesmo.
